// This file is automatically generated by Firebase Studio.
// Do not edit this file manually, as it will be overwritten.
//
// When developing locally, you can set the `GCLOUD_PROJECT` environment
// variable to specify which project's config to use.
// IMPORTANT: Replace the placeholder values with your actual Firebase project configuration.
export const firebaseConfig = {
  apiKey: 'REPLACE_WITH_YOUR_API_KEY',
  authDomain: 'REPLACE_WITH_YOUR_AUTH_DOMAIN',
  projectId: 'REPLACE_WITH_YOUR_PROJECT_ID',
  storageBucket: 'REPLACE_WITH_YOUR_STORAGE_BUCKET',
  messagingSenderId: 'REPLACE_WITH_YOUR_MESSAGING_SENDER_ID',
  appId: 'REPLACE_WITH_YOUR_APP_ID',
};
