// This file is automatically generated by Firebase Studio.
// Do not edit this file manually, as it will be overwritten.
//
// When developing locally, you can set the `GCLOUD_PROJECT` environment
// variable to specify which project's config to use.
// IMPORTANT: Replace the placeholder values with your actual Firebase project configuration.
export const firebaseConfig = {
  apiKey: "AIzaSyCjCy2tLCBNdqzgcryVMC6_1x73WCtyAzM",
  authDomain: "studio-5533261207-f5012.firebaseapp.com",
  projectId: "studio-5533261207-f5012",
  storageBucket: "studio-5533261207-f5012.appspot.com",
  messagingSenderId: "988146968348",
  appId: "1:988146968348:web:7bc095df650a77193cbcd9",
};
